FROM node:20.14.0

WORKDIR /usr/src/app
COPY package*.json ./  
# copy package.json but not the source code

# install dependancies from the cache and start the program in dev mode 
CMD npm install --prefer-offline && \
    npm run start:dev
