# Kuber Config that will be used to automatically deploy deltarune-video
# when this repo is pushed to Github. 
# 
# To deploy:
#
# export CONTAINER_REGISTRY=<your-container-registry>
# export VERSION=<the-version-to-deploy>
# envsubst < ./cd_pipeline/deploy-cd.yaml | kubectl apply -f -
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltarune-video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deltarune-video
  template:
    metadata:
      labels:
        app: deltarune-video
    spec:
      containers: 
      - name: deltarune-video
        # we use environment variables to parameterize our deployment file
        # once we set the env variables, we can use `envsubst` to replace 
        # the env variables with their values
        image: $CONTAINER_REGISTRY/deltarune-video:$VERSION
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  name: deltarune-video
spec:
  selector:
    app: deltarune-video
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
#
