FROM node:20.14.0

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --omit=dev
COPY ./src ./src 
# COPY ./videos ./videos     # no longer need to copy videos now that vids are in the cloud

# wait for rabbit to start
CMD npx wait-port rabbit:5672 && \
    npm start 
