# To deploy:
# kubectl apply -f .\kuberscripts\deploy-local.yaml

# To remove:
# kubectl delete -f .\kuberscripts\deploy-local.yaml

apiVersion: apps/v1
kind: Deployment    # deployment mode - keeps microservice alive, restarts automatically if crash
metadata:
  name: deltarune-video   # name of the deployment
spec:
  replicas: 1     # only keep a single copy running. you can increase this number for load-balancing, redundancy, and other stuff
  selector:
    matchLabels:
      app: deltarune-video    # a name to link together the deployment, pod, and service
  template:     # template for our pod?
    metadata:
      labels:
        app: deltarune-video
    spec:
      containers: 
      - name: deltarune-video
        image: deltarune-video:2    # what docker image we should use
        imagePullPolicy: Never        # we deploy locally for now, so don't need to pull from a private registry
        env:        # sets environment variables
        - name: PORT
          value: "4000"

---     # splits out config file into two? section divider of some sorts

apiVersion: v1
kind: Service   # service mode - creates a DNS record and exposes our microservice to HTTP requests
metadata:
  name: deltarune-video     # name of service
spec:
  selector:
    app: deltarune-video
  type: NodePort      # creates a Nodeport, exposing our ports outside the kube cluster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000    # maps this container's port 4000 to port 30k on your dev computer
      nodePort: 30069     # kube only allows ports in range 30k to about 32k.

