name: CI

on:
  #
  # Runs tests against the microservice on push to the main branch of this code repository.
  #
  push: 
    branches:
      - main

  #
  # Allows deployment to be invoked manually through the GitHub Actions user interface.
  #
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    # some of this code has been taken from ChatGPT's output because I'm letting Github Actions
    # run tests against my entire repo instead of just a single microservice (which is what the book does)
    - name: Checkout code
      uses: actions/checkout@v4

    # 
    # Installs Node.js for use in the workflow. Note: uses a different action than checking out the code!
    #
    - name: Set up NodeJS
      uses: actions/setup-node@v4
      #working-directory: ./deltarune-video/
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: ./deltarune-video/package-lock.json
      

    - name: Install dependencies
      run: npm ci
      working-directory: ./deltarune-video/
        
    - name: Run tests
      run: npm test
      working-directory: ./deltarune-video/
